In [2]:
ab_test <- read.csv("../dataset/raw/ab_test.csv")
head(ab_test)

  id     time    con_treat page     converted
1 851104 11:48.6 control   old_page 0
2 804228 01:45.2 control   old_page 0
3 661590 55:06.2 treatment new_page 0
4 853541 28:03.1 treatment new_page 0
5 864975 52:26.2 control   old_page 1
6 936923 20:49.1 control   old_page 0

In [3]:
countries_ab <- read.csv("../dataset/raw/countries_ab.csv")
head(countries_ab)

  id     country
1 834778 UK
2 928468 US
3 822059 UK
4 711597 UK
5 710616 UK
6 909908 UK

In [4]:
tibble::glimpse(ab_test)

Rows: 294,478
Columns: 5
$ id        <int> 851104, 804228, 661590, 853541, 864975, 936923, 679687, 7190…
$ time      <chr> "11:48.6", "01:45.2", "55:06.2", "28:03.1", "52:26.2", "20:4…
$ con_treat <chr> "control", "control", "treatment", "treatment", "control", "…
$ page      <chr> "old_page", "old_page", "new_page", "new_page", "old_page", …
$ converted <int> 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, …

In [5]:
tibble::glimpse(countries_ab)

Rows: 290,584
Columns: 2
$ id      <int> 834778, 928468, 822059, 711597, 710616, 909908, 811617, 938122…
$ country <chr> "UK", "US", "UK", "UK", "UK", "UK", "US", "US", "US", "US", "U…

In [6]:
colSums(is.na(ab_test))

       id      time con_treat      page converted
        0         0         0         0         0

In [7]:
colSums(is.na(countries_ab))

     id country
      0       0

In [8]:
sum(duplicated(ab_test$id))

[1] 3894

In [9]:
sum(duplicated(countries_ab$id))

[1] 0

In [10]:
table(ab_test$con_treat, ab_test$page)

            new_page old_page
  control       1928   145274
  treatment   145311     1965

In [11]:
dup_counts <- sort(table(ab_test$id), decreasing = TRUE)
dup_counts <- dup_counts[dup_counts > 1]
head(dup_counts)

630052 630126 630137 630320 630471 630780
     2      2      2      2      2      2

In [12]:
ab_test_clean <- ab_test[((ab_test$con_treat == 'control') & (ab_test$page == 'old_page')) | ((ab_test$con_treat == 'treatment') & (ab_test$page == 'new_page')), ]

In [13]:
sum(duplicated(ab_test_clean$id))

[1] 1

In [14]:
dup_counts <- sort(table(ab_test_clean$id), decreasing = TRUE)
dup_counts <- dup_counts[dup_counts > 1]
head(dup_counts)

773192
     2

In [15]:
ab_test_clean[ab_test_clean$id == 773192, ]

     id     time    con_treat page     converted
1900 773192 37:58.8 treatment new_page 0
2894 773192 55:59.6 treatment new_page 0

In [16]:
ab_test_clean <- ab_test_clean[!duplicated(ab_test_clean$id), ]

In [18]:
sum(duplicated(ab_test_clean$id))

[1] 0

In [19]:
table(ab_test_clean$con_treat, ab_test_clean$page)

            new_page old_page
  control          0   145274
  treatment   145310        0

In [21]:
# Simpan tanpa tanda kutip pada nilai teks
write.csv(ab_test_clean, "../dataset/cleaned/ab_test_clean.csv", row.names = FALSE, quote = FALSE)